all:
	cc -Wall -Wextra -pedantic -std=iso9899:1999 amem.c -o amem
	cc -Wall -Wextra -pedantic -std=iso9899:1999 linkedlists.c -o linkedlists
test:
	cc -Wall -Wextra -pedantic -std=iso9899:1999 test.c -o test
clean:
	rm -rfv amem a.out linkedlists
